import 'package:flutter/material.dart';

const Map<String, IconData> iconRegistry = {
  'local_gas_station': Icons.local_gas_station,
  'build': Icons.build_outlined,
  'car_repair': Icons.car_repair,
  'security': Icons.security,
  'gavel': Icons.gavel,
  'cleaning_services': Icons.cleaning_services,
  'local_parking': Icons.local_parking,
  'settings': Icons.settings,
  'receipt_long': Icons.receipt_long,
  'directions_car': Icons.directions_car,
  'electric_bolt': Icons.electric_bolt,
  'format_paint': Icons.format_paint,
  'shopping_cart': Icons.shopping_cart,
  'handyman': Icons.handyman,
  'engineering': Icons.engineering,
  'speed': Icons.speed,
  'warning': Icons.warning_amber,
  'attach_money': Icons.attach_money,
  'store': Icons.store,
  'medical_services': Icons.medical_services,
  'battery_charging_full': Icons.battery_charging_full,
  'water_drop': Icons.water_drop,
  'tire_repair': Icons.tire_repair,
  'oil_barrel': Icons.oil_barrel,
  'star': Icons.star_outline,
  'calendar_today': Icons.calendar_today,
  'local_shipping': Icons.local_shipping,
  'garage': Icons.garage,
  'home_repair_service': Icons.home_repair_service,
  'more_horiz': Icons.more_horiz,
};
